/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUB_H_RPCGEN
#define _SUB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;

#define SUB_PROG 0x30d0d0df
#define SUB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sub 1
extern  int * sub_1(numbers *, CLIENT *);
extern  int * sub_1_svc(numbers *, struct svc_req *);
extern int sub_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sub 1
extern  int * sub_1();
extern  int * sub_1_svc();
extern int sub_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUB_H_RPCGEN */
