/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "addsub.h"


void
addsub_prog_1(char *host,int x,int y)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;
	int  *result_2;
	numbers  sub_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADDSUB_PROG, ADDSUB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.a=x;
	add_1_arg.b=y;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\n %d + %d = %d",x,y,*result_1);		
	}
	sub_1_arg.a=x;
	sub_1_arg.b=y;
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\n %d - %d = %d \n",x,y,*result_2);		
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	addsub_prog_1 (host,atoi(argv[2]),atoi(argv[3]));
exit (0);
}
