print("Write a program for printing ͞yhnetobgnes͟ from ͞pythonbestforbeginners͟.")
a="pythonbestforbeginners"
print(a[1::2])
print("Write a program to print reverse of a user given string.")
a=str(input('Enter a string:'))
print("Reverse of string is "+a[::-1])
print("Write a program to change all occurrences of 3 rd character with @͟?")
a=str(input('Enter a string:'))
print(a.replace(a[3],'@'))
print("Write a program to replace a string with new string only specified number of times?")
a=str(input('Enter a string:'))
b=str(input('Enter the old string:'))
c=str(input('Enter the new string:'))
d=int(input('No of times you want to replace:'))
print(a)
print(a.replace(b,c,d))
print("Write a program that exchange value of two numbers without using temporary variable.")
a=int(input('Enter a value:'))
b=int(input('Enter b value:'))
print("Values of a=",a)
print("b=",b)
(a,b)=(b,a)
print("Values of a=",a)
print("b=",b)
print("Write a program to print character that are at multiples of 3 position in a user input string?")
a=str(input('Enter the string:'))
i=0
while (i<(len(a)-1)):
	i=i+3
	print(a[i])
